//Fuck bitch

const imageAssets = [
  // ad banners
  'assets/ads/furry.png',
  'assets/ads/kirkingmyschmeet.webp',
  'assets/ads/onlyguys.webp',
  'assets/ads/residente.png',
  'assets/ads/sexysolitaire.webp',
  'assets/ads/FakeNews.jpg',
  'assets/ads/jimmyrpe.jpg',
  'assets/ads/hapa.png',
  'assets/ads/feinwashed.webp',
  'assets/ads/yahu_is_our_savior.webp',
  'assets/ads/coolest_ad_ever.webp',
  'assets/ads/french.webp',
  'assets/ads/jimmygay.png',
  'assets/ads/Cocter.png',
  'assets/ads/saucy.png',
  'assets/ads/jimmyisverymean.jpg',
  'assets/thebuol.jpg',

  // core sprites / backgrounds
  'assets/ClaviculusTheWise.jpg',
  'assets/CardSprite.jpg',
  'assets/DealerDown.png',
  'assets/jorkinit.jpg',
  'assets/title.png',
  'assets/leave store.png',

  // backgroundmap
  'assets/vegasstrip.jpg',
  'assets/epsteintemple.jpg',
  'assets/blackingmyjack.jpg',
  'assets/MrNetanyahuNose.png',
  'assets/dump.jpg',
  'assets/oldustytrail.jpg',
  'assets/trashcarrace.png',
  'assets/syndromedown.jpg',
  'assets/carcrash.jpg',
  'assets/totallyfrhibachi.jpg',
  'assets/hibachioutside.png',
  'assets/hiubachigrill.jpg',
  'assets/evilassrapeplace.png',
  'assets/evilassrapeplace2.png',
  'assets/smthsmthracist.jpg',
  'assets/chinatown.jpg',
  'assets/oldmandying.webp',
  'assets/ohlordylord.webp',
  'assets/kindainsensitive.jpg',
  'assets/bar.jpg',
  'assets/landoffireandpainfuckinstupidasscaliforniaiHATEyou.jpg',
  'assets/waawaawoowee.png',
  'assets/ikea.jpg',
  'assets/cumbucket.jpg',
  'assets/ending.jpg',

  // spritemap
  'assets/blank-image.png',
  'assets/NoahsBarmitsvah.png',
  'assets/woowooweewee.png',
  'assets/MrNetanyahu.png',
  'assets/packson.png',
  'assets/homeless.png',
  'assets/angy.png',
  'assets/waiter.png',
  'assets/NoahsFemboyBarmitsvah.png',
  'assets/mynuts.png',
  'assets/poop.png',
  'assets/pookiewookie.png',
  'assets/eatmyasshole.png',
  'assets/asiandude.png',
  'assets/jamalkunpersona4.png',
  'assets/cardboard.png',

  // shop buttons -> 'assets/' + name + '.png'
  ...[
    'clav', 'steroids', 'nord vpn', 'yarmulke',
    'israeli flag body pillow', 'storm cosplay', 'kitty cat :3',
    'hentai game', 'penis curling', 'aderall',
    'mystery sludge', 'leave store'
  ].map((name) => `assets/${name}.png`),
];

const videoAssets = [
  'assets/erika-kirk-kirk.mp4',

  // Soundtrack
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Blackjack Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Date1 Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Date2 Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Date3 Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Ending Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Init Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Sniff Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Store Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Title Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/IJUSTHITTHEJACKPOTTTTTTT.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Combat Theme.mp3',
  'assets/KRPG2 OFFICIAL SOUNDTRACK DELUXE 1/Drunk Theme.mp3',

  // VoiceLines
  'assets/VoiceLines/Aegislash/0.mp3',
  'assets/VoiceLines/Aegislash/1.mp3',
  'assets/VoiceLines/Aegislash/2.mp3',
  'assets/VoiceLines/Aegislash/3.mp3',
  'assets/VoiceLines/Aegislash/4.mp3',
  'assets/VoiceLines/Aegislash/5.mp3',
  'assets/VoiceLines/Aegislash/6.mp3',
  'assets/VoiceLines/Aegislash/7.mp3',
  'assets/VoiceLines/Aggron/0.mp3',
  'assets/VoiceLines/Aggron/1.mp3',
  'assets/VoiceLines/Aggron/2.mp3',
  'assets/VoiceLines/Aggron/3.mp3',
  'assets/VoiceLines/Aggron/5.mp3',
  'assets/VoiceLines/Aggron/6.mp3',
  'assets/VoiceLines/Aggron/7.mp3',
  'assets/VoiceLines/Aggron/8.mp3',
  'assets/VoiceLines/Aggron/9.mp3',
  'assets/VoiceLines/Aggron/10.mp3',
  'assets/VoiceLines/Aggron/11.mp3',
  'assets/VoiceLines/Aggron/12.mp3',
  'assets/VoiceLines/Aggron/13.mp3',
  'assets/VoiceLines/Aggron/14.mp3',
  'assets/VoiceLines/aids/0.mp3',
  'assets/VoiceLines/ass car/0.mp3',
  'assets/VoiceLines/ass car/1.mp3',
  'assets/VoiceLines/azumarill/0.mp3',
  'assets/VoiceLines/azumarill/1.mp3',
  'assets/VoiceLines/azumarill/2.mp3',
  'assets/VoiceLines/azumarill/3.mp3',
  'assets/VoiceLines/azumarill/4.mp3',
  'assets/VoiceLines/bellsprout/0.mp3',
  'assets/VoiceLines/big trix poops/0.mp3',
  'assets/VoiceLines/big trix poops/1.mp3',
  'assets/VoiceLines/big trix poops/2.mp3',
  'assets/VoiceLines/big trix poops/3.mp3',
  'assets/VoiceLines/big trix poops/4.mp3',
  'assets/VoiceLines/big trix poops/5.mp3',
  'assets/VoiceLines/big trix poops/6.mp3',
  'assets/VoiceLines/big trix poops/7.mp3',
  'assets/VoiceLines/big trix poops/8.mp3',
  'assets/VoiceLines/big trix poops/9.mp3',
  'assets/VoiceLines/big trix poops/10.mp3',
  'assets/VoiceLines/big trix poops/11.mp3',
  'assets/VoiceLines/big trix poops/12.mp3',
  'assets/VoiceLines/big trix poops/13.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/0.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/1.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/2.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/4.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/5.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/6.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/7.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/8.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/9.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/10.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/11.mp3',
  'assets/VoiceLines/brian robinson, rb 1 of the falcons/12.mp3',
  'assets/VoiceLines/finale/1.mp3',
  'assets/VoiceLines/finale/2.mp3',
  'assets/VoiceLines/finale/3.mp3',
  'assets/VoiceLines/finale/4.mp3',
  'assets/VoiceLines/finale/5.mp3',
  'assets/VoiceLines/finale/6.mp3',
  'assets/VoiceLines/finale/7.mp3',
  'assets/VoiceLines/finale/8.mp3',
  'assets/VoiceLines/finale/9.mp3',
  'assets/VoiceLines/finale/10.mp3',
  'assets/VoiceLines/finale/11.mp3',
  'assets/VoiceLines/finale/12.mp3',
  'assets/VoiceLines/finale/13.mp3',
  'assets/VoiceLines/finale/14.mp3',
  'assets/VoiceLines/fine car/0.mp3',
  'assets/VoiceLines/froakie/0.mp3',
  'assets/VoiceLines/gardevoir/1.mp3',
  'assets/VoiceLines/gardevoir/2.mp3',
  'assets/VoiceLines/gardevoir/3.mp3',
  'assets/VoiceLines/ghastly/0.mp3',
  'assets/VoiceLines/goat car/0.mp3',
  'assets/VoiceLines/goat win/0.mp3',
  'assets/VoiceLines/goat win/1.mp3',
  'assets/VoiceLines/goat win/2.mp3',
  'assets/VoiceLines/goat win/3.mp3',
  'assets/VoiceLines/goat win/4.mp3',
  'assets/VoiceLines/goat win/5.mp3',
  'assets/VoiceLines/goat win/6.mp3',
  'assets/VoiceLines/goat win/7.mp3',
  'assets/VoiceLines/goat win/8.mp3',
  'assets/VoiceLines/goat win/9.mp3',
  'assets/VoiceLines/goat win/10.mp3',
  'assets/VoiceLines/goat win/11.mp3',
  'assets/VoiceLines/goat win/12.mp3',
  'assets/VoiceLines/gyarados/0.mp3',
  'assets/VoiceLines/hiv/0.mp3',
  'assets/VoiceLines/init/0.mp3',
  'assets/VoiceLines/init/1.mp3',
  'assets/VoiceLines/init/2.mp3',
  'assets/VoiceLines/init/3.mp3',
  'assets/VoiceLines/init/4.mp3',
  'assets/VoiceLines/init/5.mp3',
  'assets/VoiceLines/init/6.mp3',
  'assets/VoiceLines/init/7.mp3',
  'assets/VoiceLines/init/8.mp3',
  'assets/VoiceLines/init/9.mp3',
  'assets/VoiceLines/init/11.mp3',
  'assets/VoiceLines/init/12.mp3',
  'assets/VoiceLines/init/13.mp3',
  'assets/VoiceLines/Ivysaur/0.mp3',
  'assets/VoiceLines/Ivysaur/1.mp3',
  'assets/VoiceLines/kevin is gay/0.mp3',
  'assets/VoiceLines/kevin is gay/1.mp3',
  'assets/VoiceLines/lucario/0.mp3',
  'assets/VoiceLines/lucario/1.mp3',
  'assets/VoiceLines/lucario/2.mp3',
  'assets/VoiceLines/Medicham/0.mp3',
  'assets/VoiceLines/Medicham/1.mp3',
  'assets/VoiceLines/Medicham/2.mp3',
  'assets/VoiceLines/Medicham/3.mp3',
  'assets/VoiceLines/Medicham/4.mp3',
  'assets/VoiceLines/Medicham/5.mp3',
  'assets/VoiceLines/Medicham/6.mp3',
  'assets/VoiceLines/Medicham/7.mp3',
  'assets/VoiceLines/Medicham/8.mp3',
  'assets/VoiceLines/Mewtwo X/0.mp3',
  'assets/VoiceLines/nidoran male/0.mp3',
  'assets/VoiceLines/oddish/0.mp3',
  'assets/VoiceLines/oof/0.mp3',
  'assets/VoiceLines/oof/1.mp3',
  'assets/VoiceLines/oof/2.mp3',
  'assets/VoiceLines/oof/3.mp3',
  'assets/VoiceLines/oof/4.mp3',
  'assets/VoiceLines/oof/5.mp3',
  'assets/VoiceLines/oof/6.mp3',
  'assets/VoiceLines/oof/7.mp3',
  'assets/VoiceLines/oof/8.mp3',
  'assets/VoiceLines/oof/9.mp3',
  'assets/VoiceLines/oof/10.mp3',
  'assets/VoiceLines/oof/11.mp3',
  'assets/VoiceLines/oof/12.mp3',
  'assets/VoiceLines/Pelipper/0.mp3',
  'assets/VoiceLines/Pelipper/1.mp3',
  'assets/VoiceLines/Pelipper/2.mp3',
  'assets/VoiceLines/Pelipper/3.mp3',
  'assets/VoiceLines/Pelipper/4.mp3',
  'assets/VoiceLines/Pelipper/5.mp3',
  'assets/VoiceLines/Pelipper/6.mp3',
  'assets/VoiceLines/Pelipper/7.mp3',
  'assets/VoiceLines/Pelipper/9.mp3',
  'assets/VoiceLines/Pelipper/10.mp3',
  'assets/VoiceLines/Pelipper/11.mp3',
  'assets/VoiceLines/Pelipper/12.mp3',
  'assets/VoiceLines/peniswine/0.mp3',
  'assets/VoiceLines/peniswine/0.mp3',
  'assets/VoiceLines/peniswine/1.mp3',
  'assets/VoiceLines/peniswine/3.mp3',
  'assets/VoiceLines/peniswine/4.mp3',
  'assets/VoiceLines/peniswine/6.mp3',
  'assets/VoiceLines/peniswine/7.mp3',
  'assets/VoiceLines/peniswine/8.mp3',
  'assets/VoiceLines/peniswine/9.mp3',
  'assets/VoiceLines/peniswine/10.mp3',
  'assets/VoiceLines/peniswine/11.mp3',
  'assets/VoiceLines/peniswine/12.mp3',
  'assets/VoiceLines/peniswine/13.mp3',
  'assets/VoiceLines/peniswine/14.mp3',
  'assets/VoiceLines/peniswine/15.mp3',
  'assets/VoiceLines/peniswine/16.mp3',
  'assets/VoiceLines/peniswine/17.mp3',
  'assets/VoiceLines/peniswine/18.mp3',
  'assets/VoiceLines/peniswine/19.mp3',
  'assets/VoiceLines/peniswine/20.mp3',
  'assets/VoiceLines/peniswine/21.mp3',
  'assets/VoiceLines/peniswine/22.mp3',
  'assets/VoiceLines/peniswine/23.mp3',
  'assets/VoiceLines/peniswine/26.mp3',
  'assets/VoiceLines/peniswine/27.mp3',
  'assets/VoiceLines/peniswine/29.mp3',
  'assets/VoiceLines/peniswine/30.mp3',
  'assets/VoiceLines/peniswine/31.mp3',
  'assets/VoiceLines/peniswine/32.mp3',
  'assets/VoiceLines/peniswine/33.mp3',
  'assets/VoiceLines/peniswine/34.mp3',
  'assets/VoiceLines/peniswine/36.mp3',
  'assets/VoiceLines/peniswine/37.mp3',
  'assets/VoiceLines/peniswine/38.mp3',
  'assets/VoiceLines/peniswine/39.mp3',
  'assets/VoiceLines/peniswine/40.mp3',
  'assets/VoiceLines/peniswine/43.mp3',
  'assets/VoiceLines/peniswine/44.mp3',
  'assets/VoiceLines/peniswine/45.mp3',
  'assets/VoiceLines/peniswine/46.mp3',
  'assets/VoiceLines/peniswine/47.mp3',
  'assets/VoiceLines/peniswine/48.mp3',
  'assets/VoiceLines/peniswine/49.mp3',
  'assets/VoiceLines/peniswine/52.mp3',
  'assets/VoiceLines/peniswine/53.mp3',
  'assets/VoiceLines/peniswine/54.mp3',
  'assets/VoiceLines/peniswine/55.mp3',
  'assets/VoiceLines/peniswine/57.mp3',
  'assets/VoiceLines/peniswine/58.mp3',
  'assets/VoiceLines/peniswine/59.mp3',
  'assets/VoiceLines/peniswine/60.mp3',
  'assets/VoiceLines/peniswine/63.mp3',
  'assets/VoiceLines/peniswine/64.mp3',
  'assets/VoiceLines/pikachu/0.mp3',
  'assets/VoiceLines/shit car/0.mp3',
  'assets/VoiceLines/shit car/1.mp3',
  'assets/VoiceLines/skarmory/0.mp3',
  'assets/VoiceLines/skarmory/1.mp3',
  'assets/VoiceLines/skarmory/2.mp3',
  'assets/VoiceLines/skarmory/4.mp3',
  'assets/VoiceLines/skarmory/5.mp3',
  'assets/VoiceLines/skarmory/6.mp3',
  'assets/VoiceLines/skarmory/7.mp3',
  'assets/VoiceLines/skarmory/8.mp3',
  'assets/VoiceLines/skarmory/9.mp3',
  'assets/VoiceLines/skarmory/10.mp3',
  'assets/VoiceLines/skarmory/11.mp3',
  'assets/VoiceLines/skarmory/12.mp3',
  'assets/VoiceLines/slim win/0.mp3',
  'assets/VoiceLines/slim win/1.mp3',
  'assets/VoiceLines/slim win/2.mp3',
  'assets/VoiceLines/slim win/3.mp3',
  'assets/VoiceLines/slim win/4.mp3',
  'assets/VoiceLines/slim win/5.mp3',
  'assets/VoiceLines/slim win/6.mp3',
  'assets/VoiceLines/slim win/7.mp3',
  'assets/VoiceLines/slim win/8.mp3',
  'assets/VoiceLines/slim win/9.mp3',
  'assets/VoiceLines/slim win/10.mp3',
  'assets/VoiceLines/slim win/11.mp3',
  'assets/VoiceLines/slim win/13.mp3',
  'assets/VoiceLines/slim win/14.mp3',
  'assets/VoiceLines/sniff/0.mp3',
  'assets/VoiceLines/sniff/1.mp3',
  'assets/VoiceLines/sniff/2.mp3',
  'assets/VoiceLines/sniff/3.mp3',
  'assets/VoiceLines/sniff/4.mp3',
  'assets/VoiceLines/sniff/5.mp3',
  'assets/VoiceLines/sniff/6.mp3',
  'assets/VoiceLines/sniff/7.mp3',
  'assets/VoiceLines/sniff/8.mp3',
  'assets/VoiceLines/sniff/9.mp3',
  'assets/VoiceLines/sniff/10.mp3',
  'assets/VoiceLines/spinarak/0.mp3',
  'assets/VoiceLines/spinarak/1.mp3',
  'assets/VoiceLines/spinarak/2.mp3',
  'assets/VoiceLines/spinarak/3.mp3',
  'assets/VoiceLines/suicune/0.mp3',
  'assets/VoiceLines/suicune/1.mp3',
  'assets/VoiceLines/suicune/2.mp3',
  'assets/VoiceLines/suicune/3.mp3',
  'assets/VoiceLines/superfuck/0.mp3',
  'assets/VoiceLines/superfuck/2.mp3',
  'assets/VoiceLines/superfuck/3.mp3',
  'assets/VoiceLines/superfuck/4.mp3',
  'assets/VoiceLines/superfuck/5.mp3',
  'assets/VoiceLines/superfuck/6.mp3',
  'assets/VoiceLines/superfuck/7.mp3',
  'assets/VoiceLines/superfuck/8.mp3',
  'assets/VoiceLines/superfuck/10.mp3',
  'assets/VoiceLines/superfuck/11.mp3',
  'assets/VoiceLines/superfuck/12.mp3',
  'assets/VoiceLines/superfuck/13.mp3',
  'assets/VoiceLines/superfuck/14.mp3',
  'assets/VoiceLines/superfuck/15.mp3',
  'assets/VoiceLines/superfuck/16.mp3',
  'assets/VoiceLines/superfuck/17.mp3',
  'assets/VoiceLines/superfuck/18.mp3',
  'assets/VoiceLines/superfuck/19.mp3',
  'assets/VoiceLines/superfuck/20.mp3',
  'assets/VoiceLines/superfuck/21.mp3',
  'assets/VoiceLines/superfuck/22.mp3',
  'assets/VoiceLines/superfuck/23.mp3',
  'assets/VoiceLines/superfuck/24.mp3',
  'assets/VoiceLines/superfuck/25.mp3',
  'assets/VoiceLines/superfuck/26.mp3',
  'assets/VoiceLines/superfuck/27.mp3',
  'assets/VoiceLines/superfuck/28.mp3',
  'assets/VoiceLines/superfuck/29.mp3',
  'assets/VoiceLines/superfuck/30.mp3',
  'assets/VoiceLines/superfuck/31.mp3',
  'assets/VoiceLines/Surskit/1.mp3',
  'assets/VoiceLines/Surskit/2.mp3',
  'assets/VoiceLines/Surskit/3.mp3',
  'assets/VoiceLines/Surskit/4.mp3',
  'assets/VoiceLines/Surskit/5.mp3',
  'assets/VoiceLines/Surskit/6.mp3',
  'assets/VoiceLines/Surskit/7.mp3',
  'assets/VoiceLines/Surskit/8.mp3',
  'assets/VoiceLines/Surskit/9.mp3',
  'assets/VoiceLines/Surskit/10.mp3',
  'assets/VoiceLines/Surskit/11.mp3',
  'assets/VoiceLines/Surskit/12.mp3',
  'assets/VoiceLines/Surskit/13.mp3',
  'assets/VoiceLines/Surskit/14.mp3',
  'assets/VoiceLines/Surskit/15.mp3',
  'assets/VoiceLines/Surskit/16.mp3',
  'assets/VoiceLines/Surskit/17.mp3',
  'assets/VoiceLines/trashRace/0.mp3',
  'assets/VoiceLines/trashRace/1.mp3',
  'assets/VoiceLines/trashRace/2.mp3',
  'assets/VoiceLines/trashRace/3.mp3',
  'assets/VoiceLines/trashRace/4.mp3',
  'assets/VoiceLines/trashRace/5.mp3',
  'assets/VoiceLines/trashRace/6.mp3',
  'assets/VoiceLines/trashRace/7.mp3',
  'assets/VoiceLines/trashRace/8.mp3',
  'assets/VoiceLines/trashRace/9.mp3',
  'assets/VoiceLines/trashRace/10.mp3',
  'assets/VoiceLines/trashRace/11.mp3',
  'assets/VoiceLines/trashRace/12.mp3',
  'assets/VoiceLines/trashRace/13.mp3',
  'assets/VoiceLines/trashRace/14.mp3',
  'assets/VoiceLines/trashRace/15.mp3',
  'assets/VoiceLines/trashRace/16.mp3',
  'assets/VoiceLines/trashRace/17.mp3',
  'assets/VoiceLines/trashRace/18.mp3',
  'assets/VoiceLines/trashRace/19.mp3',
  'assets/VoiceLines/trashRace/20.mp3',
  'assets/VoiceLines/trashRace/21.mp3',
  'assets/VoiceLines/trashRace/22.mp3',
  'assets/VoiceLines/trashRace/23.mp3',
  'assets/VoiceLines/trashRace/24.mp3',
  'assets/VoiceLines/trashRace/25.mp3',
  'assets/VoiceLines/trashRace/26.mp3',
  // 'assets/VoiceLines/trashRace/27.mp3',
  'assets/VoiceLines/trashRace/28.mp3',
  'assets/VoiceLines/trashRace/29.mp3',
  'assets/VoiceLines/trashRace/30.mp3',
  'assets/VoiceLines/trashRace/31.mp3',
  'assets/VoiceLines/trashRace/32.mp3',
  'assets/VoiceLines/trevenaunt/0.mp3',
  'assets/VoiceLines/Vanillish/0.mp3',
  'assets/VoiceLines/Vanillish/1.mp3',
  'assets/VoiceLines/Vanillish/3.mp3',
  'assets/VoiceLines/Vikavolt/0.mp3',
  'assets/VoiceLines/Vikavolt/1.mp3',
  'assets/VoiceLines/Vikavolt/2.mp3',
  'assets/VoiceLines/Vikavolt/3.mp3',
  'assets/VoiceLines/Vikavolt/4.mp3',
  'assets/VoiceLines/Vikavolt/5.mp3',
  'assets/VoiceLines/Vikavolt/6.mp3',
  'assets/VoiceLines/Vikavolt/7.mp3',
  'assets/VoiceLines/Vikavolt/8.mp3',
  'assets/VoiceLines/Vikavolt/9.mp3',
  'assets/VoiceLines/Vikavolt/10.mp3',
];

// de-dupe in case any path appears more than once
const uniqueImageAssets = [...new Set(imageAssets)];
const uniqueVideoAssets = [...new Set(videoAssets)];

const totalAssets = uniqueImageAssets.length + uniqueVideoAssets.length;

const screenEl = document.getElementById('preload-screen');
const barFillEl = document.getElementById('preload-bar-fill');
const statusEl = document.getElementById('preload-status');

let loadedCount = 0;

function updateProgress() {
  loadedCount++;
  const pct = totalAssets === 0 ? 100 : Math.round((loadedCount / totalAssets) * 100);
  if (barFillEl) barFillEl.style.width = pct + '%';
  if (statusEl) statusEl.textContent = `${loadedCount} / ${totalAssets} assets loaded`;
}

function loadImage(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      updateProgress();
      resolve(img);
    };
    img.onerror = () => {
      console.warn('Failed to preload image:', src);
      updateProgress();
      resolve(null);
    };
    img.src = src;
  });
}

function loadVideo(src) {
  return new Promise((resolve) => {
    const vid = document.createElement('video');
    vid.preload = 'auto';
    vid.oncanplaythrough = () => {
      updateProgress();
      resolve(vid);
    };
    vid.onerror = () => {
      console.warn('Failed to preload video:', src);
      updateProgress();
      resolve(null);
    };
    vid.src = src;
    vid.load();
  });
}

function hideLoadingScreen() {
  if (!screenEl) return;
  screenEl.classList.add('hidden');
  setTimeout(() => {
    screenEl.style.display = 'none';
  }, 450); // matches CSS transition duration
}

async function preloadAll() {
  if (statusEl) statusEl.textContent = `0 / ${totalAssets} assets loaded`;

  const imagePromises = uniqueImageAssets.map(loadImage);
  const videoPromises = uniqueVideoAssets.map(loadVideo);

  await Promise.all([...imagePromises, ...videoPromises]);

  hideLoadingScreen();
  // let the rest of the app know assets are ready, in case game.js
  // wants to wait for this instead of / in addition to the visual cue
  window.dispatchEvent(new CustomEvent('assets-preloaded'));
}

preloadAll();